Feature branch
KingsleyMcSimon/re-former pull request #1
Opened 2020-02-10 22:37 UTC by Tekcoder

2020-02-11 01:37 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @Tekcoder @KingsleyMcSimon 

Thank you for that nice job :+1: 
However, before moving forward, kindly make those changes

1. Please, fix the stickler's errors

2. Creating a new user is not working. Please, read the comment below

3. Please, instead of `/users` I suggest you use `users_path`

Kindly make the changes and submit a new code review request,
Thanks

Mael FOSSO

2020-02-11 01:37 UTC, maelfosso commented on app/views/users/new.html.erb
> +    <%= form_for :@user do |f| %>
Because of `:@user`, creating user is not possible.
Change `:@user` to **`@user`**

2020-02-11 01:37 UTC, maelfosso commented on app/views/users/new.html.erb
> +<!-- <%= form_tag('/users') do %>-->
Change `/users` to `users_path`

2020-02-11 01:37 UTC, maelfosso commented on app/views/users/new.html.erb
> +<!-- <form action="/users" method="post" accept-charset="UTF-8">-->
It's preferable to use `users_path` instead of `/users`

2020-02-12 04:29 UTC, imhta requested changes
# Changes required 🛑 

### Hello  @Tekcoder @KingsleyMcSimon  , 👋 You have done a great job in this project 👏 

* [ ] Please, fix the stickler's errors
* [ ] Add a descriptive PR description
----
### Don't forget to request another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

2020-02-12 13:55 UTC, Tekcoder commented
> 
> # Changes required 🛑
> ### Hello @Tekcoder @KingsleyMcSimon , 👋 You have done a great job in this project 👏
> 
>     * [ ]  Please, fix the stickler's errors
> 
>     * [ ]  Add a descriptive PR description
> 
> 
> ### Don't forget to request another code review
> 
> **Pon Muthu Selvam N**
> **[nponmuthuselvam@gmail.com](mailto:nponmuthuselvam@gmail.com)**
> _If you have any queries, feel free to ping me on slack_
We don't seem to understand your review.

Firstly, there are no stickler errors but you said that we should correct fix the stickler's errors. It stated that all "All checks have passed". To confirm this, click on the Checks tab above and see where it stated "No lint errors found"

Secondly, you said that we should Add a descriptive PR description. I don't find that on the pathwright. Please what does it mean and where can we find that on the pathwright. Thank you while awaiting your reply

2020-02-12 14:36 UTC, imhta commented
- [ ] The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

##### Reference for linter issue

![image](https://user-images.githubusercontent.com/25448577/74344652-f8bf9f00-4dd2-11ea-912c-e0f3c721d8a9.png)

2020-02-12 15:51 UTC, mcrd25 approved these changes
# Changes Approved 🤓 💪 🎉 🎊 

Hi Team!

You've successfully addressed the remaining two issues! There is no need for further review, you may merge to master 🙂 .

***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-02-12 15:51 UTC, mcrd25 commented on .rubocop.yml
> +AllCops:
I suggest you use the .rubocop.yml` file for ROR istead of simply for Ruby. https://github.com/microverseinc/linters-config/blob/master/ror/.rubocop.yml (Same for stickler)

2020-02-12 16:06 UTC, merged